OPENAI_MODELS = {
    "chatgpt-4o-latest": {"name": "Chatgpt 4O Latest", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "codex-mini-latest": {"name": "Codex Mini Latest", "provider": "openai", "icon": "💻", "capabilities": ["text", "code"]},
    "dall-e-2": {"name": "Dall E 2", "provider": "openai", "icon": "🎨", "capabilities": ["text", "code"]},
    "dall-e-3": {"name": "Dall E 3", "provider": "openai", "icon": "🎨", "capabilities": ["text", "code"]},
    "gpt-3.5-turbo-16k": {"name": "Gpt 3.5 Turbo 16K", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-3.5-turbo-instruct": {"name": "Gpt 3.5 Turbo Instruct", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-4.1": {"name": "Gpt 4.1", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4.1-2025-04-14": {"name": "Gpt 4.1 2025 04 14", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4.1-mini": {"name": "Gpt 4.1 Mini", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4.1-mini-2025-04-14": {"name": "Gpt 4.1 Mini 2025 04 14", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4.1-nano": {"name": "Gpt 4.1 Nano", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4.1-nano-2025-04-14": {"name": "Gpt 4.1 Nano 2025 04 14", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o": {"name": "Gpt 4O", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-2024-05-13": {"name": "Gpt 4O 2024 05 13", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-2024-08-06": {"name": "Gpt 4O 2024 08 06", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-2024-11-20": {"name": "Gpt 4O 2024 11 20", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-audio-preview": {"name": "Gpt 4O Audio Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-audio-preview-2024-12-17": {"name": "Gpt 4O Audio Preview 2024 12 17", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-audio-preview-2025-06-03": {"name": "Gpt 4O Audio Preview 2025 06 03", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini": {"name": "Gpt 4O Mini", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-2024-07-18": {"name": "Gpt 4O Mini 2024 07 18", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-audio-preview": {"name": "Gpt 4O Mini Audio Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-audio-preview-2024-12-17": {"name": "Gpt 4O Mini Audio Preview 2024 12 17", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-realtime-preview": {"name": "Gpt 4O Mini Realtime Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-realtime-preview-2024-12-17": {"name": "Gpt 4O Mini Realtime Preview 2024 12 17", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-search-preview": {"name": "Gpt 4O Mini Search Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-search-preview-2025-03-11": {"name": "Gpt 4O Mini Search Preview 2025 03 11", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-transcribe": {"name": "Gpt 4O Mini Transcribe", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-mini-tts": {"name": "Gpt 4O Mini Tts", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-realtime-preview": {"name": "Gpt 4O Realtime Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-realtime-preview-2024-12-17": {"name": "Gpt 4O Realtime Preview 2024 12 17", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-realtime-preview-2025-06-03": {"name": "Gpt 4O Realtime Preview 2025 06 03", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-search-preview": {"name": "Gpt 4O Search Preview", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-search-preview-2025-03-11": {"name": "Gpt 4O Search Preview 2025 03 11", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-transcribe": {"name": "Gpt 4O Transcribe", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-4o-transcribe-diarize": {"name": "Gpt 4O Transcribe Diarize", "provider": "openai", "icon": "🧠", "capabilities": ["text", "code"]},
    "gpt-5": {"name": "Gpt 5", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-2025-08-07": {"name": "Gpt 5 2025 08 07", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-chat-latest": {"name": "Gpt 5 Chat Latest", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-codex": {"name": "Gpt 5 Codex", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-mini": {"name": "Gpt 5 Mini", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-mini-2025-08-07": {"name": "Gpt 5 Mini 2025 08 07", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-nano": {"name": "Gpt 5 Nano", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-nano-2025-08-07": {"name": "Gpt 5 Nano 2025 08 07", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-pro": {"name": "Gpt 5 Pro", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-pro-2025-10-06": {"name": "Gpt 5 Pro 2025 10 06", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-search-api": {"name": "Gpt 5 Search Api", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-5-search-api-2025-10-14": {"name": "Gpt 5 Search Api 2025 10 14", "provider": "openai", "icon": "🌟", "capabilities": ["text", "code"]},
    "gpt-audio": {"name": "Gpt Audio", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-audio-2025-08-28": {"name": "Gpt Audio 2025 08 28", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-audio-mini": {"name": "Gpt Audio Mini", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-audio-mini-2025-10-06": {"name": "Gpt Audio Mini 2025 10 06", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-image-1": {"name": "Gpt Image 1", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-image-1-mini": {"name": "Gpt Image 1 Mini", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-realtime": {"name": "Gpt Realtime", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-realtime-2025-08-28": {"name": "Gpt Realtime 2025 08 28", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-realtime-mini": {"name": "Gpt Realtime Mini", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "gpt-realtime-mini-2025-10-06": {"name": "Gpt Realtime Mini 2025 10 06", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "o1": {"name": "O1", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o1-2024-12-17": {"name": "O1 2024 12 17", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o1-pro": {"name": "O1 Pro", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o1-pro-2025-03-19": {"name": "O1 Pro 2025 03 19", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3": {"name": "O3", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-2025-04-16": {"name": "O3 2025 04 16", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-deep-research": {"name": "O3 Deep Research", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-deep-research-2025-06-26": {"name": "O3 Deep Research 2025 06 26", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-mini": {"name": "O3 Mini", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-mini-2025-01-31": {"name": "O3 Mini 2025 01 31", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-pro": {"name": "O3 Pro", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o3-pro-2025-06-10": {"name": "O3 Pro 2025 06 10", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o4-mini": {"name": "O4 Mini", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o4-mini-2025-04-16": {"name": "O4 Mini 2025 04 16", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o4-mini-deep-research": {"name": "O4 Mini Deep Research", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "o4-mini-deep-research-2025-06-26": {"name": "O4 Mini Deep Research 2025 06 26", "provider": "openai", "icon": "🎯", "capabilities": ["text", "code"]},
    "omni-moderation-2024-09-26": {"name": "Omni Moderation 2024 09 26", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "omni-moderation-latest": {"name": "Omni Moderation Latest", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "sora-2": {"name": "Sora 2", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "sora-2-pro": {"name": "Sora 2 Pro", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "text-embedding-3-large": {"name": "Text Embedding 3 Large", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "text-embedding-3-small": {"name": "Text Embedding 3 Small", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "text-embedding-ada-002": {"name": "Text Embedding Ada 002", "provider": "openai", "icon": "🤖", "capabilities": ["text", "code"]},
    "tts-1": {"name": "Tts 1", "provider": "openai", "icon": "🔊", "capabilities": ["text", "code"]},
    "tts-1-1106": {"name": "Tts 1 1106", "provider": "openai", "icon": "🔊", "capabilities": ["text", "code"]},
    "tts-1-hd": {"name": "Tts 1 Hd", "provider": "openai", "icon": "🔊", "capabilities": ["text", "code"]},
    "tts-1-hd-1106": {"name": "Tts 1 Hd 1106", "provider": "openai", "icon": "🔊", "capabilities": ["text", "code"]},
    "whisper-1": {"name": "Whisper 1", "provider": "openai", "icon": "🎙️", "capabilities": ["text", "code"]},
}
GEMINI_MODELS = {
    "embedding-gecko-001": {"name": "Embedding Gecko 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash": {"name": "Gemini 2.5 Flash", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-pro": {"name": "Gemini 2.5 Pro", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-exp": {"name": "Gemini 2.0 Flash Exp", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash": {"name": "Gemini 2.0 Flash", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-001": {"name": "Gemini 2.0 Flash 001", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-lite-001": {"name": "Gemini 2.0 Flash Lite 001", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-lite": {"name": "Gemini 2.0 Flash Lite", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-lite-preview-02-05": {"name": "Gemini 2.0 Flash Lite Preview 02 05", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.0-flash-lite-preview": {"name": "Gemini 2.0 Flash Lite Preview", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-exp-1206": {"name": "Gemini Exp 1206", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-preview-tts": {"name": "Gemini 2.5 Flash Preview Tts", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-pro-preview-tts": {"name": "Gemini 2.5 Pro Preview Tts", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "gemma-3-1b-it": {"name": "Gemma 3 1B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemma-3-4b-it": {"name": "Gemma 3 4B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemma-3-12b-it": {"name": "Gemma 3 12B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemma-3-27b-it": {"name": "Gemma 3 27B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemma-3n-e4b-it": {"name": "Gemma 3N E4B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemma-3n-e2b-it": {"name": "Gemma 3N E2B It", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-flash-latest": {"name": "Gemini Flash Latest", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-flash-lite-latest": {"name": "Gemini Flash Lite Latest", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-pro-latest": {"name": "Gemini Pro Latest", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-lite": {"name": "Gemini 2.5 Flash Lite", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-image-preview": {"name": "Gemini 2.5 Flash Image Preview", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-image": {"name": "Gemini 2.5 Flash Image", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-preview-09-2025": {"name": "Gemini 2.5 Flash Preview 09 2025", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-lite-preview-09-2025": {"name": "Gemini 2.5 Flash Lite Preview 09 2025", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-3-pro-preview": {"name": "Gemini 3 Pro Preview", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "gemini-3-flash-preview": {"name": "Gemini 3 Flash Preview", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-3-pro-image-preview": {"name": "Gemini 3 Pro Image Preview", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "nano-banana-pro-preview": {"name": "Nano Banana Pro Preview", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "gemini-robotics-er-1.5-preview": {"name": "Gemini Robotics Er 1.5 Preview", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-computer-use-preview-10-2025": {"name": "Gemini 2.5 Computer Use Preview 10 2025", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "deep-research-pro-preview-12-2025": {"name": "Deep Research Pro Preview 12 2025", "provider": "google", "icon": "💎", "capabilities": ["text", "multimodal"]},
    "embedding-001": {"name": "Embedding 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "text-embedding-004": {"name": "Text Embedding 004", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-embedding-exp-03-07": {"name": "Gemini Embedding Exp 03 07", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-embedding-exp": {"name": "Gemini Embedding Exp", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-embedding-001": {"name": "Gemini Embedding 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "aqa": {"name": "Aqa", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "imagen-4.0-generate-preview-06-06": {"name": "Imagen 4.0 Generate Preview 06 06", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "imagen-4.0-ultra-generate-preview-06-06": {"name": "Imagen 4.0 Ultra Generate Preview 06 06", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "imagen-4.0-generate-001": {"name": "Imagen 4.0 Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "imagen-4.0-ultra-generate-001": {"name": "Imagen 4.0 Ultra Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "imagen-4.0-fast-generate-001": {"name": "Imagen 4.0 Fast Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "veo-2.0-generate-001": {"name": "Veo 2.0 Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "veo-3.0-generate-001": {"name": "Veo 3.0 Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "veo-3.0-fast-generate-001": {"name": "Veo 3.0 Fast Generate 001", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "veo-3.1-generate-preview": {"name": "Veo 3.1 Generate Preview", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "veo-3.1-fast-generate-preview": {"name": "Veo 3.1 Fast Generate Preview", "provider": "google", "icon": "🔮", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-native-audio-latest": {"name": "Gemini 2.5 Flash Native Audio Latest", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-native-audio-preview-09-2025": {"name": "Gemini 2.5 Flash Native Audio Preview 09 2025", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
    "gemini-2.5-flash-native-audio-preview-12-2025": {"name": "Gemini 2.5 Flash Native Audio Preview 12 2025", "provider": "google", "icon": "✨", "capabilities": ["text", "multimodal"]},
}


# Claude Extended
CLAUDE_MODELS = {
    "claude-3-5-sonnet-20241022": {"name": "Claude 3.5 Sonnet", "provider": "anthropic", "icon": "🎭", "capabilities": ["text", "code"]},
    "claude-3-5-haiku-20241022": {"name": "Claude 3.5 Haiku", "provider": "anthropic", "icon": "⚡", "capabilities": ["text", "fast"]},
    "claude-3-opus-20240229": {"name": "Claude 3 Opus", "provider": "anthropic", "icon": "💎", "capabilities": ["text", "code"]},
}

# Ollama Local
OLLAMA_MODELS = {
    "qwen2.5-coder:7b": {"name": "VibeAI Go Coder", "provider": "ollama", "icon": "🦙", "capabilities": ["code", "local"]},
    "llama3.2:3b": {"name": "VibeAI Go Chat", "provider": "ollama", "icon": "🦙", "capabilities": ["text", "local"]},
}

ALL_EXTENDED = {**OPENAI_MODELS, **GEMINI_MODELS, **CLAUDE_MODELS, **OLLAMA_MODELS}

def get_extended_models():
    return [{'id': k, **v} for k, v in ALL_EXTENDED.items()]
