#!/bin/bash

echo "🚀 VibeAI - GitHub Repository Setup"
echo "===================================="
echo ""
echo "📋 Quick Setup Guide:"
echo ""
echo "OPTION 1 - GitHub CLI (empfohlen):"
echo "-----------------------------------"
echo "1. Führe aus: gh auth login"
echo "2. Wähle: GitHub.com → HTTPS → Yes → Login with browser"
echo "3. Dann: ./github_setup.sh"
echo ""
echo "OPTION 2 - Manuell auf GitHub.com:"
echo "-----------------------------------"
echo "1. Gehe zu: https://github.com/new"
echo "2. Repository Name: vibeai"
echo "3. Description: 🚀 Premium AI App Development Studio"
echo "4. Public ✅"
echo "5. NICHT 'Initialize with README' (haben wir schon!)"
echo "6. Klicke 'Create repository'"
echo ""
echo "7. Dann im Terminal:"
echo "   cd /Users/mikegehrke/Development/vibeai"
echo "   git remote add origin https://github.com/DEIN-USERNAME/vibeai.git"
echo "   git push -u origin main"
echo ""
echo "📊 Was wird hochgeladen:"
echo "   - 112 Dateien"
echo "   - 22.828 Zeilen Code"
echo "   - 3 Studios (App Builder, Code Studio, App Studio)"
echo "   - AI Chat mit History"
echo "   - Monaco Editor"
echo "   - Live Preview"
echo "   - Git Integration"
echo ""
echo "Welche Option möchtest du verwenden?"
