# -------------------------------------------------------------
# VIBEAI – FLUTTER PROJECT GENERATOR
# -------------------------------------------------------------
"""
Flutter Project Generator

Creates complete Flutter projects with:
- Material Design template
- pubspec.yaml configuration
- Main app structure
- Assets directory
- Test structure
- Analysis options
"""

import os
from typing import Dict, Optional

from project_generator.base_writer import writer


class FlutterProjectGenerator:
    """
    Generate complete Flutter mobile/web projects.

    Features:
    - Material Design UI
    - Hot reload ready
    - Cross-platform (iOS, Android, Web, Desktop)
    - Modern Flutter 3.x
    """

    def create_project(self, base_path: str, project_name: str, options: Optional[Dict] = None) -> Dict:
        """
        Create complete Flutter project.

        Args:
            base_path: Project root directory
            project_name: Project name (snake_case)
            options: {
                "description": "App description",
                "org": "com.example",
                "platforms": ["android", "ios", "web"]
            }

        Returns:
            {
                "success": True,
                "files_created": 12,
                "project_path": "/path/to/project"
            }
        """
        if options is None:
            options = {}

        try:
            # Create directory structure
            self._create_structure(base_path)

            # Write configuration files
            self._write_config(base_path, project_name, options)

            # Write main app
            self._write_main(base_path, project_name, options)

            # Write additional files
            self._write_extras(base_path, project_name)

            # Get stats
            stats = writer.get_project_stats(base_path)

            return {
                "success": True,
                "files_created": stats["total_files"],
                "project_path": base_path,
                "framework": "flutter",
            }

        except Exception as e:
            return {"success": False, "error": str(e), "framework": "flutter"}

    def _create_structure(self, base_path: str):
        """Create Flutter directory structure."""
        structure = [
            "lib",
            "lib/screens",
            "lib/widgets",
            "lib/models",
            "test",
            "assets",
            "assets/images",
            "android",
            "ios",
            "web",
        ]

        writer.create_structure(base_path, structure)

    def _write_config(self, base_path: str, name: str, options: Dict):
        """Write Flutter configuration files."""

        description = options.get("description", f"A Flutter project generated by VibeAI")

        # pubspec.yaml
        pubspec = f"""name: {name}
description: {description}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
"""

        # analysis_options.yaml
        analysis = """include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
"""

        # README.md
        readme = f"""# {name}

{description}

## Getting Started

This is a Flutter project generated by VibeAI.

### Prerequisites

- Flutter SDK 3.3.0 or higher
- Dart SDK

### Installation