# backend/git_sync.py
# Automatischer Push zu GitHub über GitPython

from git import Repo


def push_to_github(project_path: str):
    """
    Erstellt lokales Git-Repo, committet Änderungen und pusht.
    In dieser Version nur lokal – Remote kann später per Token ergänzt werden.
    """
    try:
        repo = Repo.init(project_path)
        repo.git.add(A=True)
        repo.index.commit("Auto-generated by VibeAI Core 0.1")
        return "local_repo_initialized"
    except Exception as e:
        return f"error: {str(e)}"