# -------------------------------------------------------------
# VIBEAI – FLUTTER PROJECT GENERATOR
# -------------------------------------------------------------
"""
Flutter Project Generator

Creates complete Flutter projects with:
- Material Design template
- pubspec.yaml configuration
- Main app structure
- Assets directory
- Test structure
- Analysis options
"""

import os
from typing import Dict, Optional
from project_generator.base_writer import writer


class FlutterProjectGenerator:
    """
    Generate complete Flutter mobile/web projects.
    
    Features:
    - Material Design UI
    - Hot reload ready
    - Cross-platform (iOS, Android, Web, Desktop)
    - Modern Flutter 3.x
    """

    def create_project(
        self,
        base_path: str,
        project_name: str,
        options: Optional[Dict] = None
    ) -> Dict:
        """
        Create complete Flutter project.
        
        Args:
            base_path: Project root directory
            project_name: Project name (snake_case)
            options: {
                "description": "App description",
                "org": "com.example",
                "platforms": ["android", "ios", "web"]
            }
        
        Returns:
            {
                "success": True,
                "files_created": 12,
                "project_path": "/path/to/project"
            }
        """
        if options is None:
            options = {}

        try:
            # Create directory structure
            self._create_structure(base_path)
            
            # Write configuration files
            self._write_config(base_path, project_name, options)
            
            # Write main app
            self._write_main(base_path, project_name, options)
            
            # Write additional files
            self._write_extras(base_path, project_name)
            
            # Get stats
            stats = writer.get_project_stats(base_path)
            
            return {
                "success": True,
                "files_created": stats["total_files"],
                "project_path": base_path,
                "framework": "flutter"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "framework": "flutter"
            }

    def _create_structure(self, base_path: str):
        """Create Flutter directory structure."""
        structure = [
            "lib",
            "lib/screens",
            "lib/widgets",
            "lib/models",
            "test",
            "assets",
            "assets/images",
            "android",
            "ios",
            "web"
        ]
        
        writer.create_structure(base_path, structure)

    def _write_config(
        self,
        base_path: str,
        name: str,
        options: Dict
    ):
        """Write Flutter configuration files."""
        
        description = options.get(
            "description",
            f"A Flutter project generated by VibeAI"
        )
        
        # pubspec.yaml
        pubspec = f"""name: {name}
description: {description}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
"""
        
        # analysis_options.yaml
        analysis = """include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
"""
        
        # README.md
        readme = f"""# {name}

{description}

## Getting Started

This is a Flutter project generated by VibeAI.

### Prerequisites

- Flutter SDK 3.3.0 or higher
- Dart SDK

### Installation

```bash
flutter pub get
```

### Run

```bash
# Run on Chrome (web)
flutter run -d chrome

# Run on Android
flutter run

# Run on iOS
flutter run -d ios
```

### Build

```bash
# Build APK
flutter build apk

# Build web
flutter build web

# Build iOS
flutter build ios
```

## Features

- Material Design
- Hot Reload
- Cross-platform
- Built with VibeAI

## Project Structure

```
lib/
├── main.dart           # Entry point
├── screens/            # UI screens
├── widgets/            # Reusable widgets
└── models/             # Data models

test/                   # Unit tests
assets/                 # Images, fonts
```
"""
        
        files = {
            "pubspec.yaml": pubspec,
            "analysis_options.yaml": analysis,
            "README.md": readme,
            ".gitignore": self._get_gitignore()
        }
        
        writer.batch_write(base_path, files)

    def _write_main(
        self,
        base_path: str,
        name: str,
        options: Dict
    ):
        """Write main.dart and app structure."""
        
        app_name = options.get("app_name", name.replace("_", " ").title())
        
        main_dart = f"""import 'package:flutter/material.dart';

void main() {{
  runApp(const MyApp());
}}

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{app_name}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }}
}}

class HomeScreen extends StatefulWidget {{
  const HomeScreen({{super.key}});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}}

class _HomeScreenState extends State<HomeScreen> {{
  int _counter = 0;

  void _incrementCounter() {{
    setState(() {{
      _counter++;
    }});
  }}

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('{app_name}'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Welcome to VibeAI',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20),
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }}
}}
"""
        
        writer.write_file(os.path.join(base_path, "lib/main.dart"), main_dart)

    def _write_extras(self, base_path: str, name: str):
        """Write additional files."""
        
        # Test file
        test_file = f"""import 'package:flutter_test/flutter_test.dart';
import 'package:{name}/main.dart';

void main() {{
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {{
    await tester.pumpWidget(const MyApp());
    
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);
    
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();
    
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  }});
}}
"""
        
        writer.write_file(
            os.path.join(base_path, "test/widget_test.dart"),
            test_file
        )

    def _get_gitignore(self) -> str:
        """Get Flutter .gitignore content."""
        return """# Flutter/Dart
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub-cache/
.pub/
build/
*.lock

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Generated files
*.g.dart
*.freezed.dart
*.config.dart

# Coverage
coverage/

# Android
android/.gradle/
android/captures/
android/local.properties
android/app/release/

# iOS
ios/Pods/
ios/.symlinks/
ios/Flutter/Flutter.framework
ios/Flutter/Flutter.podspec
"""


# Global instance
flutter_project = FlutterProjectGenerator()
