# -------------------------------------------------------------
# FLUTTER PROJECT TEMPLATE
# -------------------------------------------------------------
"""Flutter project templates and boilerplate."""

from typing import Dict, Optional


class FlutterTemplate:
    """Flutter project template generator."""

    def get_pubspec(self, name: str, options: Optional[Dict]) -> str:
        """Generate pubspec.yaml."""
        return f"""name: {name}
description: A VibeAI generated Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
"""

    def get_main(self, name: str, options: Optional[Dict]) -> str:
        """Generate main.dart."""
        return """import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VibeAI App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('VibeAI App'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Welcome to VibeAI',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {},
              child: const Text('Get Started'),
            ),
          ],
        ),
      ),
    );
  }
}
"""

    def get_readme(self, name: str) -> str:
        """Generate README.md."""
        return f"""# {name}

A Flutter application generated by VibeAI.

## Getting Started