# -------------------------------------------------------------
# REACT PROJECT TEMPLATE
# -------------------------------------------------------------
"""React project templates and boilerplate."""

import json
from typing import Dict, Optional


class ReactTemplate:
    """React project template generator."""

    def get_package_json(self, name: str, options: Optional[Dict] = None) -> str:
        """Generate package.json."""
        package = {
            "name": name,
            "private": True,
            "version": "1.0.0",
            "type": "module",
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview",
            },
            "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0"},
            "devDependencies": {"@vitejs/plugin-react": "^4.2.0", "vite": "^5.0.0"},
        }

        return json.dumps(package, indent=2)

    def get_index_html(self, name: str) -> str:
        """Generate index.html."""
        return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.jsx"></script>
  </body>
</html>
"""

    def get_app_jsx(self, name: str, options: Optional[Dict] = None) -> str:
        """Generate App.jsx."""
        return """import { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to VibeAI</h1>
        <p>Your React app is ready!</p>

        <div className="card">
          <button onClick={() => setCount((count) => count + 1)}>
            count is {count}
          </button>
        </div>
      </header>
    </div>
  );
}

export default App;
"""

    def get_index_jsx(self) -> str:
        """Generate index.jsx."""
        return """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"""

    def get_vite_config(self) -> str:
        """Generate vite.config.js."""
        return """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: '0.0.0.0'
  }
});
"""

    def get_readme(self, name: str) -> str:
        """Generate README.md."""
        return f"""# {name}

A React application generated by VibeAI.

## Getting Started